version: "3"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finantial_module
    networks:
      - dev

  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    networks:
      - dev

  localstack:
    image: localstack/localstack:3.1
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=sns,sqs,s3,lambda
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack:/etc/localstack/init/ready.d
    networks:
      - dev

  localstack-web:
    image: dantasrafael/localstack-web:0.0.1
    ports:
      - "3000:80"
    environment:
      - VITE_LOCALSTACK_ENDPOINT=http://localhost:4566
      - VITE_AWS_DEFAULT_REGION=us-east-1
      - VITE_AWS_ACCESS_KEY_ID=test
      - VITE_AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    networks:
      - dev

networks:
  dev:

volumes:
  pgdata:
