-- DROP SCHEMA
DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students;

-- DROP types
DROP TYPE IF EXISTS ACCOUNT_STATUS;

-- DROP UUID EXTENSION
DROP EXTENSION IF EXISTS "uuid-ossp";
